common: &common
  access_key_id:     'skdjbnfksdjfkjsdnf'
  secret_access_key: 'shhh'
  region:            'eu-west-1'

defaults: &defaults
  photos:
    <<: *common
    bucket_name: 'photoport-eu'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
