development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: photoport_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: photoport_test
  username: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: photoport_production
  username: postgres
  pool: 5
  timeout: 5000